Move outputs to outside of container

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,19 @@ runs:
           -e SKIP_SECRETS=1 \
           -e SKIP_SERVICES=1 \
           --entrypoint=/src/entrypoint.sh ${{ inputs.dockerImage }}
+        outputFile="${{ inputs.targetDir }}/phpunit-results.txt"
+        SUCCESS=$(cat $outputFile | grep -q OK && echo 'true' || echo 'false')
+        SUMMARY=$(grep -i 'assertions' "$outputFile" | grep -i 'tests')
+        RESULT_TEXT=$([ "$SUCCESS" == "true" ] && echo "PASS" || echo "FAIL")
+        RESULT_EMOJI=$([ "$SUCCESS" == "true" ] && echo ':white_check_mark:' || echo ':x:')
+        
+        echo SUCCESS="${SUCCESS}"
+        echo SUMMARY="${SUMMARY}"
+        
+        echo "::set-output name=success::${SUCCESS}"
+        echo "::set-output name=summary::${SUMMARY}"
+        echo "::set-output name=result-text::${RESULT_TEXT}"
+        echo "::set-output name=result-emoji::${RESULT_EMOJI}"
 
       shell: bash
 inputs:
